void main()
{
	ADCON1=0x0F;
	CMCON=7;
	TRISA.RA0=1;		//INPUT TO DETECT HIGH LEVEL
	TRISA.RA1=1;		//INPUT TO DETECT LOW LEVEL
	TRISB=0x00;		//PORT B AS OUTPUT TO GLOW LEDs AND BUZZER
	WHILE(1)
	{
		IF(PORTA.RA0==1 && PORTA.RA1==1)	//HIGH LEVEL DETECTED
		{
			PORTB.RB1=0;
			PORTB.RB0=1;			//GREEN LED WILL GLOW
		}
		ELSE IF(PORTA.RA0==0 && PORTRA1==0)	//LOW LEVEL DETECTED
		{
			PORTB.RB0=0;
			PORTB.RB1=1;			//RED LED AND BUZZER WILL GET ON
		}
		ELSE
		{
			PORTB.RB0=0;		//BOTH LEDs AND BUZZER WILL BE OFF
			PORTB.RB1=0;
		}
	}
}
